name: Java Gradle Testing and building

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      ##- name: Run unit tests
        ##run: ./gradlew test
      ##- name: Run integration test
        ##run: ./gradlew integrationTest

  building:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/final-0.0.1-SNAPSHOT.jar

  publish:
    needs: building
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: build/libs

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:development-latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:development-latest
          
  system-testing:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run system-testing
        run: ./gradlew systemTest
    services:
      app:
        image: ghcr.io/petertalling/devops-final:development-latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:80
        options: --health-cmd="curl -f http://localhost:80" --health-interval=10s --health-timeout=5s --health-retries=3

        
  deploy:
    needs: system-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Deploy Fake
        run: echo "Deploying ghcr.io/${{ env.REPO_NAME }}:development-latest"
